### PR TITLE
Reduce macro expansion forms of ok/ng

### PR DESCRIPTION
**Pull request by fukamachi**
@cxxxr

### CODE REVIEW

**Comment by cxxxr** [comment]
I've tried this branch. but the compiler will still die.

How to reproduce the procedure.

1. git clone https://github.com/lem-project/lem, git checkout workbench-test
2. git clone https://github.com/fukamachi/rove.git, git checkout reduce-macro-expansion
2. Enter the following equation in repl `(ql:quickload :lem-tests)`

This part seems to be the problem. https://github.com/lem-project/lem/blob/58f156646c2c1fb880fb2130aae0f4cbf6ad11d1/tests/string-width-utils.lisp#L43-L46

**Comment by fukamachi** [comment]
Thanks for trying this out!
Bad news, but I'll look into it.

**Comment by fukamachi** [comment]
It found out the problem is not because of the size of expanded forms.
SBCL will be stuck on too many `handler-bind` + `restart-case` forms even those body is simple, like:

```common-lisp
(defun run ()
  (handler-bind ((error (lambda (e) (declare (ignore e)))))
    (restart-case (+ 1 2)
      (ignore () nil)))
  (handler-bind ((error (lambda (e) (declare (ignore e)))))
    (restart-case (+ 1 2)
      (ignore () nil)))

  ... (repeat many times)

  )
```

**Comment by fukamachi** [comment]
Similar bug report: https://bugs.launchpad.net/sbcl/+bug/1886817

**Comment by fukamachi** [comment]
@cxxxr
Could you please check this out again?
I made some changes, and now lem-tests can be loaded with f5e334195e596f1e02e341bbaa37214021069ebc on my machine.

**Comment by cxxxr** [comment]
I tried again, but the error seems to be in the same place.

When all causes are commented out
https://github.com/lem-project/lem/actions/runs/1706090925

When I turn off the comment out
https://github.com/lem-project/lem/actions/runs/1706102843

**Comment by fukamachi** [comment]
Thanks, can you add `-v` option to `ros` command to show more logs?

**Comment by cxxxr** [comment]
I've added an option.

https://github.com/lem-project/lem/runs/4836388584?check_suite_focus=true

**Comment by fukamachi** [comment]
Hmm, unfortunately, it seems nothing I can do in Rove anymore.
This is not because of the size of an expanded form, but because SBCL consumes much memory to compile blocks (ex. handler-bind, handler-case, restart-bind, or restart-case). GC is disabled while compiling the body.

It'd be better to report a bug report to SBCL, but I left a note for a workaround:

* Split assertions into several `deftest`s
  * To reduce blocks in body
  * It's okay to rewrite it with `loop`
* Raise `dynamic-space-size`
  * Though I know it's already `2048`, seems not enough

**Comment by fukamachi** [comment]
I'm still not sure what's going on in SBCL, however, it works on my forked repo.
https://github.com/fukamachi/lem/runs/4890808486?check_suite_focus=true

Using `flet` in the assertion macro will make SBCL stuck. (Perhaps it is because `flet` makes a named block?)

**Comment by cxxxr** [comment]
https://github.com/lem-project/lem/pull/570
With this change, the problem has been solved and lem can now use rove.
Thank you.

**Pull request merged**
